frontend:
  - "src/components/**"
  - "src/styles/**"
  - "src/assets/**"

screens:
  - "src/components/screens/**"

config:
  - ".github/**"
  - "**/tsconfig*.json"
  - "**/.eslintrc*"
  - "**/.prettierrc*"
  - "**/.env*"
  - "**/*.config.js"
  - "**/*.config.ts"

docs:
  - "**/*.md"
  - "docs/**"

tests:
  - "__tests__/**"
  - "**/*.spec.ts"
  - "**/*.test.ts"
  - "**/*.spec.js"
  - "**/*.test.js"
